#!/usr/bin/env python

import difflib
import glob
import os
import subprocess
import sys

from StringIO import StringIO


MUMBLER_HOME = os.environ.get('MUMBLER_HOME')
if not MUMBLER_HOME:
    raise Exception('MUMBLER_HOME environment variable not set')


os.chdir(os.path.dirname(os.path.abspath(__file__)))

MUMBER_BIN = os.path.join(MUMBLER_HOME, 'bin/mumbler')

for mumbler_script in glob.glob("*.mumbler"):
    output = subprocess.check_output([MUMBER_BIN, mumbler_script],
                                     universal_newlines=True)
    with open(os.path.splitext(mumbler_script)[0] + '.output') as truth_file:
        diff = difflib.unified_diff([l.strip() for l in truth_file.readlines()],
                                    output.splitlines(),
                                    lineterm='')
        diff = list(diff)
        if diff:
            print mumbler_script
            print '\n'.join(diff)
        else:
            sys.stdout.write('.')
            sys.stdout.flush()
