Mumbler is a lisp programming language to try out the [[http://openjdk.java.net/projects/graal/][Graal JIT]] for the JVM.

* The Language
Mumbler is a very small lisp modeled after Scheme but with far fewer special forms and built-in functions. Here is the "[[http://cesquivias.github.io/blog/2014/10/13/writing-a-language-in-truffle-part-1-a-simple-slow-interpreter/#mumbler-language][Mumbler language specification]]".

* Build
Mumbler uses [[http://gradle.org/][Gradle]] as the build system. To build the code simply run

#+begin_src shell-script
    cd graal
    ./gradlew installDist
#+end_src

* Run
Mumbler requires a special version of the JVM. You can download a [[http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html][graal JVM]] from Oracle. Mumbler requires version 0.14 or greater.

You can start Mumbler's REPL from the build directory. Just set ~JAVA_HOME~ to point to the Graal JVM.

#+begin_src shell-script
    JAVA_HOME=<graal-vm-dir> ${MUMBLER_REPO}/lang/build/install/mumbler/bin/mumbler
#+end_src

** Run benchmarks
[[sec:build][Build]] Truffle and Mumbler and [[sec:env-var][set environment variables]].

#+begin_src shell-script
    ${MUMBLER_REPO}/benchmark/measure <benchmark-name>
#+end_src

The ~benchmark-name~ is the name of one of the directories under benchmark.

** Run tests
The test/ directory contains several Mumbler scripts that try out different features. To run all the tests:

#+begin_src shell-script
    ${MUMBLER_REPO}/test/run_tests
#+end_src

** Set Environment Variables
To run Mumbler's scripts use three environment variables.

#+begin_example
    GRAAL_HOME : The directory of the Graal VM. If this is empty JAVA_HOME will be used.
    MUMBLER_HOME : The path where gradle built and installed Mumbler. It should be under ${MUMBLER_HOME}/lang/build/install/mumbler
#+end_example

* License

Copyright © 2014 Cristian Esquivias

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
