* TruffleMumbler
** Run benchmarks
[[sec:build][Build]] Truffle and Mumbler and [[sec:env-var][set environment variables]].

#+begin_src shell-script
    ./benchmark/measure <benchmark-name>
#+end_src

The ~benchmark-name~ is the name of one of the directories under benchmark/.

** Run tests
[[sec:build][Build]] Truffle and Mumbler and [[sec:env-var][set environment variables]].

The test/ directory contains several Mumbler scripts that try different features. To run all the tests:

#+begin_src shell-script
    ./test/run_tests
#+end_src

<<sec:env-var>>
** Set Environment Variables
Mumbler's scripts use two environment variables.

#+begin_example
    GRAAL_HOME : The directory of the Graal VM. If this is empty JAVA_HOME will be used.
    MUMBLER_JRE : The path to the bundled jar of Mumbler
#+end_example

<<sec:build>>
** Build
Requirements:
  - [[http://hg.openjdk.java.net/graal/graal/file/tip/][Current branch]] of Truffle
  - [[http://mercurial.selenic.com/downloads][Mercurial]]
  - [[http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html][Java 7]]
  - [[http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html][Java 8]]
  - [[http://www.antlr.org/download.html][ANTLR4]] runtime library

Follow the instruction for [[https://wiki.openjdk.java.net/display/Graal/Instructions][building Truffle]] from their wiki. Follow the instructions to [[https://wiki.openjdk.java.net/display/Graal/Eclipse][set up Eclipse]]. See [[http://cesquivias.github.io/blog/2014/12/02/writing-a-language-in-truffle-part-2-using-truffle-and-graal/#installing-graal--truffle][my notes]] as well if you run into problems.

Once you have Truffle set up with Eclipse you can import the Eclipse project for [[https://github.com/cesquivias/mumbler/tree/master/graal][TruffleMumbler]] into Eclipse. You'll need to change the location of your annotation processor jar and make sure the JRE System Library used is the Graal VM you built.

*** Installing the Truffle's annotation processing

Be sure to follow the instructions to set up Eclipse before proceeding. In Eclipse select the Mumbler project then go to the menu and select ~Project -> Properties~. Under the *Properties* window go to ~Java Compiler -> Annotation Processing~ select *Enable project specific settings*. Then select *Enable annotation processing* and *Enable processing in editor*.

Go to ~Java Compiler -> Annotation Processing -> Factory Path~ and select *Enable project specific settings* then click *Add External JARs...*. Under the directory you built Graal go to ~${GRAAL_DIR}/graal/com.oracle.truffle.dsl.processor/ap/com.oracle.truffle.dsl.processor.jar~ and add it.

*** Changing the JRE System Library

Be sure to build Graal before proceeding. In Eclipse select the Mumbler project then go to the menu and select ~Project -> Properties~. Under the *Properties* window go to ~Java Build Path~. Go to the *Libraries* tab. Remove the current System Library. Click *Add Library*. Select *JRE System Library* and click *Next >*. Select *Alternate JRE* and select the Graal VM you built (e.g., graal-1.8.0_25).



* SimpleMumbler:

#+begin_src shell-script
    ./simple/repl [mumbler script]
#+end_src

The REPL is started with no argument.

Requires:
  - java
  - javac
  - ant


* License

Copyright © 2014 Cristian Esquivias

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
