* TruffleMumbler
** Run benchmarks
[[sec:build][Build]] Truffle and Mumbler and [[sec:env-var][set environment variables]].

#+begin_src shell-script
    ./benchmark/measure <benchmark-name>
#+end_src

The ~benchmark-name~ is the name of one of the directories under benchmark/.

** Run tests
[[sec:build][Build]] Truffle and Mumbler and [[sec:env-var][set environment variables]].

The test/ directory contains several Mumbler scripts that try different features. To run all the tests:

#+begin_src shell-script
    ./test/run_tests
#+end_src

<<sec:env-var>>
** Set Environment Variables
To run Mumbler's scripts use three environment variables.

#+begin_example
    GRAAL_HOME : The directory of the Graal VM. If this is empty JAVA_HOME will be used.
    MUMBLER_JRE : The path to the bundled jar of Mumbler
#+end_example

<<sec:build>>
** Build
*** Build Truffle & Graal
Follow the instruction for [[https://wiki.openjdk.java.net/display/Graal/Instructions][building Truffle]] from their wiki. Follow the instructions to [[https://wiki.openjdk.java.net/display/Graal/Eclipse][set up Eclipse]]. See [[http://cesquivias.github.io/blog/2014/12/02/writing-a-language-in-truffle-part-2-using-truffle-and-graal/#installing-graal--truffle][my notes]] as well if you run into problems.

*** Build Mumbler with Maven
[[sec:env-var][Set the environment variables]] first. Set the TRUFFLE_DSL_JAR environment variable as well. Set it to the full path of Truffle's annotation processor JAR. If you built Graal using the wiki instructions it's located at ~${GRAAL_DIR}/graal/com.oracle.truffle.dsl.processor/ap/com.oracle.truffle.dsl.processor.jar~. After those 3 environment variables are set just run.

#+begin_src shell-script
    mvn package
#+end_src

The Mumbler jar will be located under ~target/mumbler-0.1-with-dependencies.jar~.

You can start Mumbler by
#+begin_src shell-script
    ${GRAAL_HOME}/bin/java -graal -jar target/mumbler-0.1-with-dependencies.jar
#+end_src

* SimpleMumbler:

#+begin_src shell-script
    ./simple/repl [mumbler script]
#+end_src

The REPL is started with no argument.

Requires:
  - java
  - javac
  - ant


* License

Copyright © 2014 Cristian Esquivias

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
